### PR TITLE
feat: feature: isEqual. Adds the isEqual function. All tests passing …

### PR DESCRIPTION
**Pull request by petesamper**
Bit lengthy, I'd like to refactor this at some point, but all tests pass.

issue #4

### CODE REVIEW

**Comment by johnptmcdonald** [comment]
I added another test that isEqual needs to pass. Pull this change from this repo into your local repo, then push back up to your fork.

You may need to do a recursive solution to isEqual. It's difficult to check if two objects are identical in JS, so this function will make it easy.

**Comment by petesamper** [comment]
Another potential solution I found is to utilize the [_.isEqual](https://stackoverflow.com/questions/31683075/how-to-do-a-deep-comparison-between-2-objects-with-lodash) function from Lodash which tells you if two objects are equal by value even if they have multiple levels of nesting. This would also resolve issue #8.

I'm happy to implement a recursive solution too, if you'd prefer not to rely on an external library since this is essentially what we're recreating.

**Comment by johnptmcdonald** [comment]
Let's recreate it

**Comment by petesamper** [comment]
Changes are in. :point_up_2:

Would you like us to squash commits?

**Comment by johnptmcdonald** [comment]
I can do the squashing when I merge into master

**Pull request merged**
